language: java

jdk:
  - oraclejdk7

before_script:
  - git clone https://github.com/icclab/watchtower-common.git watchtower-common
  - cd watchtower-common
  - mvn clean install -DskipTests=true
  - cd ..
  - rm -rf watchtower-common

after_success:
  - mvn clean test jacoco:report coveralls:report
